<Project>
  <Import Project="../../Directory.Build.props" />
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)../../artifacts/transport/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)../../artifacts/transport/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
